[package]
name = "rust-pachyderm"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]

[dependencies]
protobuf = "2.0.4"
grpcio = "0"

[build-dependencies]
protoc-rust = "2.0.4"
